# Generated by Django 3.1.2 on 2021-10-04 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_status', models.IntegerField()),
                ('valor_total', models.FloatField()),
                ('faixa_horario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('icon_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=220)),
                ('cpf', models.CharField(max_length=11)),
                ('localizacao', models.CharField(max_length=200, null=True)),
                ('tipo_usuario', models.CharField(max_length=200, null=True)),
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('foto_perfil', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paginas.media')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas.usuario')),
                ('ramos_interesse', models.ManyToManyField(to='paginas.Ramo')),
            ],
            bases=('paginas.usuario',),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paginas.usuario')),
                ('endereco_profissional', models.CharField(max_length=200)),
                ('ramos_atuacao', models.ManyToManyField(to='paginas.Ramo')),
            ],
            bases=('paginas.usuario',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.usuario')),
                ('likes', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('midias', models.ManyToManyField(to='paginas.Media')),
                ('ramo', models.ManyToManyField(to='paginas.Ramo')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('faixa_horario', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('medias', models.ManyToManyField(to='paginas.Media')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.pedido')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.colaborador')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.cliente'),
        ),
    ]
