# Generated by Django 4.0.1 on 2022-01-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='midias',
        ),
        migrations.AddField(
            model_name='post',
            name='midias',
            field=models.ManyToManyField(to='app.Media'),
        ),
    ]
