# Generated by Django 4.0.1 on 2022-01-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debeauty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='faixa_horario',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='horario_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='ramo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='debeauty.ramo'),
        ),
    ]
