# Generated by Django 4.0.1 on 2022-02-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debeauty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='media',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='media',
            field=models.ManyToManyField(to='debeauty.Media'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='profile_photo',
            field=models.ImageField(default='media/profile.png', upload_to=''),
        ),
    ]
