# Generated by Django 4.0.1 on 2022-01-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debeauty', '0002_remove_solicitacao_faixa_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ramo',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='ramo',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
