# Generated by Django 4.0.1 on 2022-01-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debeauty', '0005_remove_pedido_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
