# Generated by Django 4.0.1 on 2022-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debeauty', '0006_pedido_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='media',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='media',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
