# Generated by Django 4.0.1 on 2022-02-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debeauty', '0008_solicitacao_cod_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_pedido',
            field=models.DateField(default='2022-02-01'),
            preserve_default=False,
        ),
    ]
